### PR TITLE
Add community-event page

### PR DESCRIPTION
**Pull request by Jonas00000**
Depends on #113

### CODE REVIEW

**Comment by TimothyGillespie** [comment]
There have been a couple of changes on #113, but that should be easily mergable. Mostly, the usage of `dayjs(...).utc().format(...)` instead of just `daysjs(...).format(...)`. That solves a few issues.

**Comment by TheCzar1994** [comment]
FYI - I made additional updates to #113 which would change where the information for this is pulled. I think you could merge my branch into this?

**Comment by Jonas00000** [comment]
@TheCzar1994 I remerged your branch, this should be good now

**Comment by Pixelguymm** [comment]
You might want to add this page under "Posts & Info".

**Review by Pixelguymm — APPROVED** [review]

**Pull request merged**
